apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  labels:
    app: room-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: room-service

  template:
    metadata:
      labels:
        app: room-service

    spec:
      containers:
        - name: room-service
          image: sanketshetty23/room-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: classroom-config
            - secretRef:
                name: classroom-secret

          env:
            - name: SERVER_PORT
              value: "8081"

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "450Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5