apiVersion: v1
kind: Secret
metadata:
  name: classroom-secret

type: Opaque

stringData:
  DB_USER: "admin"
  DB_PASSWORD: "admin123"

  JWT_SECRET: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS_123456"

  APP_SECURITY_PASSWORD: "booking-pass"